In [1]:
import sys
sys.path.append('../')
from benji_girgs import generation, points, utils
import networkit as nk
import networkx as nx
import numpy as np
import os

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from girg_sampling import girgs

In [82]:
import importlib
importlib.reload(generation)
importlib.reload(points)

<module 'benji_girgs.generation' from '../benji_girgs/generation.py'>

<module 'benji_girgs.points' from '../benji_girgs/points.py'>

In [2]:
n = 1500
d = 3
tau = 2.1
alpha=1.2
desiredAvgDegree=100.0

g, edges, weights, pts_torus, const = generation.generate_GIRG_nk(n, d, tau, alpha, desiredAvgDegree=desiredAvgDegree, points_type=points.PointsTorus)
print(const)
utils.avg_degree(g)
print()

g, edges, weights, pts_torus2, _ = generation.generate_GIRG_nk(n, d, tau, alpha, points_type=points.PointsTorus2, weights=weights, const=const)
print(_)
utils.avg_degree(g)

g, edges, weights, pts_torus2, _ = generation.generate_GIRG_nk(n, d, tau, alpha, points_type=points.PointsMCD, weights=weights, const=const)
print(_)
utils.avg_degree(g)

PointsMixed = points.get_points_simple_mixed_class([[0], [1], [2]])
g, edges, weights, pts_mixed, _ = generation.generate_GIRG_nk(n, d, tau, alpha, points_type=PointsMixed, weights=weights, const=const)
print(_)
utils.avg_degree(g)


const_in: 1.6455078125
1.5144326256908276


../benji_girgs/generation.py:66: RuntimeWarning: divide by zero encountered in true_divide
  p_uv = np.divide(outer, dists**d)


100.072


const_in: 19.952987613828288
1.5144326256908276


99.56666666666666

const_in: 19.952987613828288
1.5144326256908276


100.30933333333333

const_in: 19.952987613828288
1.5144326256908276


99.464

In [8]:
super(points.PointsTorus)

<super: benji_girgs.points.PointsTorus, None>

In [12]:
class A:
    x = 3
    
class B(A):
    x = 4
    
super(A)
super(B)
B.__mro__

<super: __main__.A, None>

<super: __main__.B, None>

(__main__.B, __main__.A, object)

In [4]:
g, edges, weights, pts_torus, const = generation.generate_GIRG_nk(n, d, tau, alpha, desiredAvgDegree=desiredAvgDegree, points_type=generation.PointsTorus)
print(const)
nk.overview(g)
print()


gmcd, edges, weights, pts_mcd, _ = generation.generate_GIRG_nk(n, d, tau, alpha, points_type=points.PointsMCD, weights=weights, const=const)
print(_)
nk.overview(gmcd)
print()

PointsMixed = points.get_points_simple_mixed_class([[0], [1], [2]])

gmixed, edges, weights, pts_mixed, _ = generation.generate_GIRG_nk(n, d, tau, alpha, points_type=PointsMixed, weights=weights, const=const)
print(_)
nk.overview(gmixed)

const_in: 2.099609375
1.85544785144151
Network Properties:
nodes, edges			1500, 75101
directed?			False
weighted?			False
isolated nodes			0
self-loops			0
density				0.066801
clustering coefficient		0.595532
min/max/avg degree		23, 1499, 100.134667
degree assortativity		-0.267707
number of connected components	1
size of largest component	1500 (100.00 %)

const_in: 25.45930170310434
1.85544785144151
Network Properties:
nodes, edges			1500, 75099
directed?			False
weighted?			False
isolated nodes			0
self-loops			0
density				0.066799
clustering coefficient		0.548746
min/max/avg degree		23, 1499, 100.132000
degree assortativity		-0.268286
number of connected components	1
size of largest component	1500 (100.00 %)

const_in: 25.45930170310434
1.85544785144151
Network Properties:
nodes, edges			1500, 75012
directed?			False
weighted?			False
isolated nodes			0
self-loops			0
density				0.066722
clustering coefficient		0.545847
min/max/avg degree		24, 1499, 100.016000
degree assortativity		

In [81]:
print(const)

1.9967871811125821


In [80]:
points_type = PointsMixed
points_type is points.PointsMCD
points_type is points.PointsTorus2
points_type is points.Points
points_type is PointsMixed


False

False

False

True

In [72]:
type(pts_mixed)

benji_girgs.points.get_points_simple_mixed_class.<locals>.PointsSimpleMixed

In [74]:
super(PointsMixed)

<super: benji_girgs.points.get_points_simple_mixed_class.<locals>.PointsSimpleMixed,
        None>

In [45]:
pts_mixed
pts_mixed2 = points.PointsMCD(pts_mixed)

PointsSimpleMixed([[0.75264804, 0.1352038 , 0.11783772],
                   [0.6327861 , 0.26886542, 0.36455299],
                   [0.13189501, 0.61360042, 0.91070511],
                   ...,
                   [0.5844465 , 0.62881741, 0.13351104],
                   [0.40914267, 0.65697185, 0.83048334],
                   [0.29107895, 0.53718195, 0.92848699]])

In [46]:
pts_mixed.dists()

array([[0.    , 0.824 , 0.9277, ..., 0.4497, 0.9736, 0.912 ],
       [0.824 , 0.    , 0.9897, ..., 0.641 , 0.9404, 0.966 ],
       [0.9277, 0.9897, 0.    , ..., 0.4446, 0.618 , 0.4712],
       ...,
       [0.4497, 0.641 , 0.4446, ..., 0.    , 0.541 , 0.77  ],
       [0.9736, 0.9404, 0.618 , ..., 0.541 , 0.    , 0.7837],
       [0.912 , 0.966 , 0.4712, ..., 0.77  , 0.7837, 0.    ]],
      dtype=float16)

In [50]:
pts_mixed2.dists()

array([[0.    , 0.824 , 0.9277, ..., 0.4497, 0.9736, 0.912 ],
       [0.824 , 0.    , 0.9897, ..., 0.6406, 0.9404, 0.966 ],
       [0.9277, 0.9897, 0.    , ..., 0.4446, 0.618 , 0.4712],
       ...,
       [0.4497, 0.6406, 0.4446, ..., 0.    , 0.5405, 0.77  ],
       [0.9736, 0.9404, 0.618 , ..., 0.5405, 0.    , 0.7837],
       [0.912 , 0.966 , 0.4712, ..., 0.77  , 0.7837, 0.    ]],
      dtype=float16)

In [48]:
pts_mixed2.dists() == pts_mixed.dists()

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ..., False,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True, False,  True, ...,  True, False,  True],
       [ True,  True,  True, ..., False,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [51]:
np.all(pts_mixed == pts_mixed2)

PointsSimpleMixed(True)

In [53]:
r1 = points.get_dists_mixed(pts_mixed, pts_mixed.my_groups)
r2 = points.get_dists_mcd(pts_mixed)

In [56]:
np.all(r1==r2)

True

In [62]:
prod = 1
for group in pts_mixed.my_groups:
    prod *= (1 - (2*r1)**len(group))
out = 1 - prod

In [63]:
out

array([[0.    , 0.5596, 0.799 , ..., 0.0908, 0.923 , 0.7593],
       [0.5596, 0.    , 0.97  , ..., 0.2632, 0.831 , 0.9004],
       [0.799 , 0.97  , 0.    , ..., 0.0879, 0.2363, 0.1045],
       ...,
       [0.0908, 0.2632, 0.0879, ..., 0.    , 0.1582, 0.456 ],
       [0.923 , 0.831 , 0.2363, ..., 0.1582, 0.    , 0.481 ],
       [0.7593, 0.9004, 0.1045, ..., 0.456 , 0.481 , 0.    ]],
      dtype=float16)

In [67]:
np.max(np.abs(1 - (1 - 2*r2)**d - out))

0.0004883

array([[0.     , 0.1196 , 0.207  , ..., 0.01569, 0.287  , 0.189  ],
       [0.1196 , 0.     , 0.345  , ..., 0.04834, 0.2236 , 0.2683 ],
       [0.207  , 0.345  , 0.     , ..., 0.01514, 0.04297, 0.01807],
       ...,
       [0.01569, 0.04834, 0.01514, ..., 0.     , 0.02783, 0.0918 ],
       [0.287  , 0.2236 , 0.04297, ..., 0.02783, 0.     , 0.09814],
       [0.189  , 0.2683 , 0.01807, ..., 0.0918 , 0.09814, 0.     ]],
      dtype=float16)

In [171]:
dists = pts_torus2.dists()
outer = np.outer(weights, weights)
p_uv = np.divide(outer, dists**d)
p_uv = np.power(p_uv, alpha)
2**alpha * p_uv



/scratch/tmp.16422045.bdayan/ipykernel_83698/2338277511.py:3: RuntimeWarning: divide by zero encountered in true_divide
  p_uv = np.divide(outer, dists**d)


array([[          inf,  196.43523835,    4.15165675, ...,   14.27642653,
           7.73747536,    3.71263045],
       [ 196.43523835,           inf,   16.44582805, ...,   56.55097778,
          23.57871262,   14.42412862],
       [   4.15165675,   16.44582805,           inf, ..., 1553.31298284,
          22.15591491,   52.62068183],
       ...,
       [  14.27642653,   56.55097778, 1553.31298284, ...,           inf,
          70.27803278,  147.69489623],
       [   7.73747536,   23.57871262,   22.15591491, ...,   70.27803278,
                  inf,   34.67139463],
       [   3.71263045,   14.42412862,   52.62068183, ...,  147.69489623,
          34.67139463,           inf]])

In [172]:
temp = points.PointsTorus(pts_torus2)
p_uv = np.divide(outer, temp.dists()**d)
p_uv = np.power(p_uv, alpha)
p_uv

/scratch/tmp.16422045.bdayan/ipykernel_83698/3538706781.py:2: RuntimeWarning: divide by zero encountered in true_divide
  p_uv = np.divide(outer, temp.dists()**d)


array([[          inf,  196.43523835,    4.15165675, ...,   14.27642653,
           7.73747536,    3.71263045],
       [ 196.43523835,           inf,   16.44582805, ...,   56.55097778,
          23.57871262,   14.42412862],
       [   4.15165675,   16.44582805,           inf, ..., 1553.31298284,
          22.15591491,   52.62068183],
       ...,
       [  14.27642653,   56.55097778, 1553.31298284, ...,           inf,
          70.27803278,  147.69489623],
       [   7.73747536,   23.57871262,   22.15591491, ...,   70.27803278,
                  inf,   34.67139463],
       [   3.71263045,   14.42412862,   52.62068183, ...,  147.69489623,
          34.67139463,           inf]])

In [170]:
temp.dists() == dists/2

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [169]:
temp.dists()**1

array([[0.     , 0.04443, 0.4082 , ..., 0.3994 , 0.4138 , 0.46   ],
       [0.04443, 0.     , 0.3633 , ..., 0.3555 , 0.4583 , 0.416  ],
       [0.4082 , 0.3633 , 0.     , ..., 0.0083 , 0.1782 , 0.05225],
       ...,
       [0.3994 , 0.3555 , 0.0083 , ..., 0.     , 0.1865 , 0.06055],
       [0.4138 , 0.4583 , 0.1782 , ..., 0.1865 , 0.     , 0.126  ],
       [0.46   , 0.416  , 0.05225, ..., 0.06055, 0.126  , 0.     ]],
      dtype=float16)

In [157]:
pts_torus2.dists()

array([[0.     , 0.08887, 0.8164 , ..., 0.799  , 0.8276 , 0.92   ],
       [0.08887, 0.     , 0.7266 , ..., 0.711  , 0.9165 , 0.832  ],
       [0.8164 , 0.7266 , 0.     , ..., 0.0166 , 0.3564 , 0.1045 ],
       ...,
       [0.799  , 0.711  , 0.0166 , ..., 0.     , 0.373  , 0.1211 ],
       [0.8276 , 0.9165 , 0.3564 , ..., 0.373  , 0.     , 0.252  ],
       [0.92   , 0.832  , 0.1045 , ..., 0.1211 , 0.252  , 0.     ]],
      dtype=float16)

In [160]:
temp = points.PointsTorus(pts_torus2)
np.divide(outer, temp**d)

PointsTorus([[ 3.90501887, 10.9442259 ,  4.04127405, ..., 11.06786171,
               6.88282294,  4.14871081],
             [12.64116731, 35.42820032, 13.08224702, ..., 35.82842909,
              22.28079281, 13.43003689],
             [ 1.44834565,  4.05914094,  1.4988818 , ...,  4.10499664,
               2.55279347,  1.53872938],
             ...,
             [ 3.93139146, 11.01813785,  4.06856684, ..., 11.14260863,
               6.92930616,  4.17672917],
             [ 3.05698985,  8.56753541,  3.16365533, ...,  8.66432199,
               5.38812245,  3.2477607 ],
             [ 1.57667073,  4.41878547,  1.63168443, ...,  4.46870403,
               2.77897388,  1.67506256]])

In [123]:
n = 3000
d = 1
tau = 2.1
alpha=1.2

g, edges, weights, pts_torus = generation.generate_GIRG_nk(n, d, tau, alpha, points_type=generation.PointsTorus)
nk.overview(g)
print()

gmcd, _, _, pts_mcd = generation.generate_GIRG_nk(n, d, tau, alpha, points_type=generation.PointsMCD)
nk.overview(gmcd)

ValueError: too many values to unpack (expected 4)

In [3]:
gnk, edges, weights, pts, const = generation.cgirg_gen(n, d, tau, alpha, const=1.0)
nk.overview(gnk)

Network Properties:
nodes, edges			2000, 70222
directed?			False
weighted?			False
isolated nodes			0
self-loops			0
density				0.035129
clustering coefficient		0.598088
min/max/avg degree		10, 1871, 70.222000
degree assortativity		-0.225294
number of connected components	1
size of largest component	2000 (100.00 %)


In [27]:
%time g, edges, weights, pts_torus = generation.generate_GIRG_nk(n, d, tau, alpha, points_type=generation.PointsTorus)

CPU times: user 3.1 s, sys: 553 ms, total: 3.65 s
Wall time: 3.66 s


In [28]:
%time gnk, edges, weights, pts, const = generation.cgirg_gen(n, d, tau, alpha, const=1.0)

CPU times: user 1.57 s, sys: 13.1 ms, total: 1.59 s
Wall time: 1.58 s


In [12]:
nk.overview(g)

Network Properties:
nodes, edges			5000, 853351
directed?			False
weighted?			False
isolated nodes			0
self-loops			0
density				0.068282
clustering coefficient		0.519725
min/max/avg degree		89, 4999, 341.340400
degree assortativity		-0.250697
number of connected components	1
size of largest component	5000 (100.00 %)


In [13]:
nk.overview(gnk)

Network Properties:
nodes, edges			5000, 930054
directed?			False
weighted?			False
isolated nodes			0
self-loops			0
density				0.074419
clustering coefficient		0.523071
min/max/avg degree		94, 4999, 372.021600
degree assortativity		-0.254009
number of connected components	1
size of largest component	5000 (100.00 %)


In [47]:
with open('temp.txt', 'w') as file:
    file.write('0 1\n')
    file.write('0 4\n')
    file.write('1 3\n')

gtemp = nk.readGraph("temp.txt", nk.Format.EdgeListSpaceZero)
list(gtemp.iterEdges())
gtemp.numberOfNodes()
list(gtemp.iterNodes())

4

4

4

[(0, 1), (0, 4), (1, 3)]

5

[0, 1, 2, 3, 4]

In [35]:
g.hasEdge(0, 370)

False

In [36]:
g.numberOfNodes()

1000

In [38]:
g.addNodes(3)

1002

In [39]:
g.numberOfNodes()

1003

In [11]:
foo = generation.get_points_simple_mixed_class([[0], [1,2]])

In [25]:
bar = np.random.uniform(0, 2, size=(8, 3))
bar2 = foo(bar)
bar2

PointsSimpleMixed([[1.22010167, 1.35753903, 0.07077548],
                   [0.63908041, 0.6286227 , 1.69046924],
                   [0.80439659, 0.58043568, 1.8179019 ],
                   [1.2527601 , 0.63847198, 1.40840882],
                   [0.82508387, 0.8233363 , 1.64939036],
                   [0.67112787, 1.05623239, 0.56008547],
                   [0.95013865, 1.6348424 , 0.48463203],
                   [0.757315  , 0.3295371 , 0.81775366]])

In [26]:
bar2.dists()

array([[0.     , 0.5806 , 0.4155 , 0.0332 , 0.3945 , 0.4893 , 0.2695 ,
        0.4624 ],
       [0.5806 , 0.     , 0.1279 , 0.2822 , 0.186  , 0.03174, 0.311  ,
        0.11816],
       [0.4155 , 0.1279 , 0.     , 0.4102 , 0.021  , 0.1333 , 0.146  ,
        0.04688],
       [0.0332 , 0.2822 , 0.4102 , 0.     , 0.2412 , 0.582  , 0.3027 ,
        0.4956 ],
       [0.3945 , 0.186  , 0.021  , 0.2412 , 0.     , 0.1543 , 0.125  ,
        0.0679 ],
       [0.4893 , 0.03174, 0.1333 , 0.582  , 0.1543 , 0.     , 0.2793 ,
        0.0864 ],
       [0.2695 , 0.311  , 0.146  , 0.3027 , 0.125  , 0.2793 , 0.     ,
        0.1929 ],
       [0.4624 , 0.11816, 0.04688, 0.4956 , 0.0679 , 0.0864 , 0.1929 ,
        0.     ]], dtype=float16)

In [28]:
1.2201 - 0.6711

0.5489999999999999

In [29]:
0.56 - 0.0707

0.48930000000000007

In [15]:
generation.get_dists_mixed(np.arange(6).reshape(2, 3), [[0], [1,2]])

array([[ 0.  , -1.74],
       [-1.74,  0.  ]], dtype=float16)

In [16]:
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
n = 1000
d = 3
tau = 2.1
alpha=1.5

g, edges, weights, pts_torus = generation.generate_GIRG_nk(n, d, tau, alpha, points_type=generation.PointsTorus)
g, edges, weights, pts_mcd = generation.generate_GIRG_nk(n, d, tau, alpha, points_type=generation.PointsMCD)

In [84]:
%time g, edges, weights, pts = generation.generate_GIRG_nk(n, 2, tau, alpha,\
    points_type=generation.PointsMCD)
nk.overview(g)

CPU times: user 428 ms, sys: 2.01 ms, total: 430 ms
Wall time: 434 ms
Network Properties:
nodes, edges			1000, 208380
directed?			False
weighted?			False
isolated nodes			0
self-loops			0
density				0.417177
clustering coefficient		0.613198
min/max/avg degree		261, 999, 416.760000
degree assortativity		-0.094802
number of connected components	1
size of largest component	1000 (100.00 %)


In [85]:
%time g, edges, weights, pts = generation.generate_GIRG_nk(n, 2, tau, alpha,\
    points_type=generation.PointsTorus)
nk.overview(g)

CPU times: user 205 ms, sys: 1.01 ms, total: 206 ms
Wall time: 207 ms
Network Properties:
nodes, edges			1000, 67576
directed?			False
weighted?			False
isolated nodes			0
self-loops			0
density				0.135287
clustering coefficient		0.668137
min/max/avg degree		38, 999, 135.152000
degree assortativity		-0.283884
number of connected components	1
size of largest component	1000 (100.00 %)


In [53]:
np.nonzero(edges.astype(np.bool))

(array([  0,   0,   0, ..., 996, 997, 998]),
 array([  1,   2,   3, ..., 998, 999, 999]))

In [59]:
%time g, edges, weights, pts = generation.generate_GIRG_nk(n, d, tau, alpha,\
    const=1.0, points_type=generation.PointsMCD)
nk.overview(g)

CPU times: user 817 ms, sys: 23 ms, total: 840 ms
Wall time: 846 ms
Network Properties:
nodes, edges			1000, 401694
directed?			False
weighted?			False
isolated nodes			0
self-loops			0
density				0.804192
clustering coefficient		0.829399
min/max/avg degree		672, 999, 803.388000
degree assortativity		-0.041244
number of connected components	1
size of largest component	1000 (100.00 %)


In [66]:
np.nonzero(edges[6])[0]

array([  7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  20,  21,
        22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,
        35,  36,  37,  39,  40,  41,  42,  44,  45,  46,  48,  49,  51,
        52,  54,  55,  56,  59,  61,  64,  65,  67,  68,  69,  70,  71,
        72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  96,  97,  98,
        99, 100, 101, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 164, 165, 166, 167,
       168, 171, 172, 174, 175, 176, 177, 178, 179, 181, 182, 183, 184,
       185, 186, 187, 188, 189, 190, 192, 193, 195, 196, 197, 198, 200,
       201, 202, 203, 204, 206, 207, 209, 210, 211, 212, 213, 21

In [41]:
%time g, edges, weights, pts = generation.generate_GIRG_nk(n, d, tau, alpha,\
    const=1.0, points_type=generation.PointsMCD)
nk.overview(g)

CPU times: user 835 ms, sys: 31 ms, total: 866 ms
Wall time: 871 ms
Network Properties:
nodes, edges			1000, 400314
directed?			False
weighted?			False
isolated nodes			0
self-loops			0
density				0.801429
clustering coefficient		0.826463
min/max/avg degree		667, 999, 800.628000
degree assortativity		-0.039739
number of connected components	1
size of largest component	1000 (100.00 %)


In [38]:
%time g, edges, weights, pts = generation.generate_GIRG_nk(n, d, tau, alpha,\
    points_type=generation.PointsTorus)
nk.overview(g)

CPU times: user 354 ms, sys: 12 ms, total: 366 ms
Wall time: 368 ms
Network Properties:
nodes, edges			1000, 100160
directed?			False
weighted?			False
isolated nodes			0
self-loops			0
density				0.200521
clustering coefficient		0.630926
min/max/avg degree		71, 999, 200.320000
degree assortativity		-0.272148
number of connected components	1
size of largest component	1000 (100.00 %)


In [16]:
%time edges_torus = generation.generateEdges(weights, pts_torus, alpha)

CPU times: user 191 ms, sys: 2.95 ms, total: 194 ms
Wall time: 192 ms


In [15]:
%time edges_mcd = generation.generateEdges(weights, pts_mcd, alpha)

CPU times: user 198 ms, sys: 4 ms, total: 202 ms
Wall time: 201 ms


In [18]:
edges_mcd.shape
edges_mcd.sum()

397495

In [20]:
%time g1 = nk.nxadapter.nx2nk(nx.from_numpy_array(edges_mcd))

CPU times: user 1.38 s, sys: 42.9 ms, total: 1.42 s
Wall time: 1.42 s


In [21]:
%time g2 = nk.nxadapter.nx2nk(nx.from_numpy_array(edges_torus))

CPU times: user 327 ms, sys: 14.1 ms, total: 341 ms
Wall time: 339 ms


In [25]:
%time edge_list = generation.upper_triangular_to_edgelist(edges_mcd)

CPU times: user 1.61 s, sys: 20.9 ms, total: 1.63 s
Wall time: 1.63 s


In [26]:
%time edge_list = generation.upper_triangular_to_edgelist_faster(edges_mcd)

CPU times: user 399 ms, sys: 18.9 ms, total: 418 ms
Wall time: 430 ms


In [27]:
%time edge_list = generation.upper_triangular_to_edgelist_fastest(edges_mcd)

CPU times: user 82 ms, sys: 14 ms, total: 96 ms
Wall time: 94.2 ms


In [19]:
import networkx as nx

In [11]:
%time generation.generatePositions(n, d)

CPU times: user 218 µs, sys: 1.01 ms, total: 1.23 ms
Wall time: 854 µs


array([[3.92693435, 4.58836006, 3.25621345],
       [2.72533896, 9.67319996, 6.79932768],
       [0.57288787, 7.58438266, 1.09876933],
       ...,
       [5.91810748, 7.96035845, 1.06463879],
       [5.64371023, 6.21507555, 6.02381359],
       [0.20929571, 3.19504931, 3.82947699]])

In [38]:
g, edges, weights, pts = generation.generate_GIRG_nk(n, d, tau, alpha, points_type=generation.PointsMCD)

In [39]:
nk.overview(g)

Network Properties:
nodes, edges			1000, 397175
directed?			False
weighted?			False
isolated nodes			0
self-loops			0
density				0.795145
clustering coefficient		0.821629
min/max/avg degree		669, 999, 794.350000
degree assortativity		-0.041848
number of connected components	1
size of largest component	1000 (100.00 %)


In [78]:
%time g, edges, weights, pts = generation.generate_GIRG_nk(5000, d, tau, alpha, points_type=generation.PointsMCD)

CPU times: user 31.7 s, sys: 1.43 s, total: 33.1 s
Wall time: 33.1 s


In [75]:
%time g, edges, weights, pts = generation.generate_GIRG_nk(5000, d, tau, alpha, points_type=generation.PointsTorus)

CPU times: user 7.8 s, sys: 638 ms, total: 8.43 s
Wall time: 8.43 s


In [76]:
%time generation.get_dists_mcd(pts)

CPU times: user 735 ms, sys: 71 ms, total: 806 ms
Wall time: 801 ms


array([[0.     , 1.232  , 2.766  , ..., 4.17   , 2.396  , 4.555  ],
       [1.232  , 0.     , 0.10547, ..., 2.047  , 1.164  , 3.363  ],
       [2.766  , 0.10547, 0.     , ..., 0.875  , 2.504  , 3.148  ],
       ...,
       [4.17   , 2.047  , 0.875  , ..., 0.     , 1.375  , 4.023  ],
       [2.396  , 1.164  , 2.504  , ..., 1.375  , 0.     , 0.965  ],
       [4.555  , 3.363  , 3.148  , ..., 4.023  , 0.965  , 0.     ]],
      dtype=float16)

In [77]:
%time generation.get_dists_julia(pts)

CPU times: user 769 ms, sys: 138 ms, total: 907 ms
Wall time: 902 ms


array([[0.   , 6.22 , 6.938, ..., 5.125, 5.266, 7.945],
       [6.22 , 0.   , 4.766, ..., 7.883, 3.422, 7.914],
       [6.938, 4.766, 0.   , ..., 7.78 , 4.14 , 5.6  ],
       ...,
       [5.125, 7.883, 7.78 , ..., 0.   , 6.812, 8.37 ],
       [5.266, 3.422, 4.14 , ..., 6.812, 0.   , 7.35 ],
       [7.945, 7.914, 5.6  , ..., 8.37 , 7.35 , 0.   ]], dtype=float16)

In [57]:
%time generation.get_dists(pts, n**(1/d))

CPU times: user 2.4 s, sys: 928 ms, total: 3.32 s
Wall time: 3.32 s


array([[0.        , 1.5444265 , 6.13851183, ..., 6.05848187, 4.52113299,
        2.40886363],
       [1.5444265 , 0.        , 4.65052628, ..., 4.57049631, 3.25786356,
        3.95329013],
       [6.13851183, 4.65052628, 0.        , ..., 2.59595139, 2.70662657,
        5.11148082],
       ...,
       [6.05848187, 4.57049631, 2.59595139, ..., 0.        , 4.69742204,
        3.97664403],
       [4.52113299, 3.25786356, 2.70662657, ..., 4.69742204, 0.        ,
        3.73508107],
       [2.40886363, 3.95329013, 5.11148082, ..., 3.97664403, 3.73508107,
        0.        ]])

In [64]:
pts.dtype

dtype('float64')

In [59]:
%time generation.get_dists_julia(pts)

CPU times: user 722 ms, sys: 119 ms, total: 842 ms
Wall time: 834 ms


array([[0.   , 1.547, 7.516, ..., 7.266, 5.758, 7.594],
       [1.547, 0.   , 8.03 , ..., 8.53 , 7.305, 8.55 ],
       [7.516, 8.03 , 0.   , ..., 7.453, 7.297, 6.11 ],
       ...,
       [7.266, 8.53 , 7.453, ..., 0.   , 5.695, 7.855],
       [5.758, 7.305, 7.297, ..., 5.695, 0.   , 4.54 ],
       [7.594, 8.55 , 6.11 , ..., 7.855, 4.54 , 0.   ]], dtype=float16)

In [60]:
%time generation.get_dists_mcd(pts)

CPU times: user 736 ms, sys: 126 ms, total: 862 ms
Wall time: 858 ms


array([[0.    , 1.266 , 0.953 , ..., 0.0625, 2.57  , 1.969 ],
       [1.266 , 0.    , 2.438 , ..., 1.609 , 3.836 , 0.703 ],
       [0.953 , 2.438 , 0.    , ..., 0.0781, 1.758 , 1.984 ],
       ...,
       [0.0625, 1.609 , 0.0781, ..., 0.    , 2.297 , 6.03  ],
       [2.57  , 3.836 , 1.758 , ..., 2.297 , 0.    , 3.734 ],
       [1.969 , 0.703 , 1.984 , ..., 6.03  , 3.734 , 0.    ]],
      dtype=float16)

In [8]:
%time g, edges, weights, pts = generation.generate_GIRG_nk(10000, d, tau, alpha, points_type=generation.PointsTorus)

CPU times: user 14.2 s, sys: 2.25 s, total: 16.5 s
Wall time: 16.5 s


In [9]:
%time g, edges, weights, pts = generation.generate_GIRG_nk(n, d, tau, alpha, points_type=generation.PointsTorus)

CPU times: user 309 ms, sys: 50 ms, total: 359 ms
Wall time: 357 ms


In [10]:
%time g, edges, weights, pts = generation.generate_GIRG_nk(n, 5, tau, alpha, points_type=generation.PointsTorus)

CPU times: user 963 ms, sys: 30.8 ms, total: 994 ms
Wall time: 993 ms


In [13]:
%time g, edges, weights, pts = generation.generate_GIRG_nk(2000, 5, tau, alpha, points_type=generation.PointsTorus)

CPU times: user 2.93 s, sys: 136 ms, total: 3.07 s
Wall time: 3.07 s
